name: BlizzardCore
version: 0.5-SNAPSHOT
main: me.dominator.alert.Main
depend: [LilyPad-Connect]
commands:
  alert:
    description: Alert to all servers
  dispatch:
    description: Dispatch commands
  a:
    description: Talk in staff chat
  info:
    description: Get the plugin info